name: planka

services:
  planka:
    build: .
    image: bigtechid/task:2.2.1
    container_name: planka
    restart: unless-stopped
    mem_limit: 1536m
    cpus: 1.5
    mem_reservation: 768m
    env_file:
      - planka.env
    volumes:
      - planka_data:/app/data
      - ./server/terms/custom:/app/terms/custom:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.planka.rule=Host(`task.bigtech.id`)"
      - "traefik.http.routers.planka.entrypoints=websecure"
      - "traefik.http.routers.planka.tls=true"
      - "traefik.http.routers.planka.tls.certresolver=letsencrypt"
      - "traefik.http.services.planka.loadbalancer.server.port=1337"
      - "traefik.docker.network=traefik"

volumes:
  planka_data:

networks:
  traefik:
    external: true
